# Generated by Django 6.1.1 on 2026-09-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="book",
            name="inventory_non_negative",
        ),
        migrations.AlterField(
            model_name="book",
            name="inventory",
            field=models.PositiveIntegerField(),
        ),
    ]
