# Generated by Django 6.1.1 on 2026-09-18 20:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0002_alter_book_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Borrowing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "borrow_date",
                    models.DateField(
                        default=django.utils.timezone.localdate, editable=False
                    ),
                ),
                ("expected_return_date", models.DateField()),
                ("actual_return_date", models.DateField(blank=True, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowings",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-borrow_date", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("expected_return_date__gte", models.F("borrow_date"))
                        ),
                        name="expected_return_not_before_borrow",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("actual_return_date__isnull", True),
                            ("actual_return_date__gte", models.F("borrow_date")),
                            _connector="OR",
                        ),
                        name="actual_return_not_before_borrow",
                    ),
                ],
            },
        ),
    ]
